routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


Route::get('/master', function () {
    return view('layouts.master');
});

Route::resource('/thing', \App\Http\Controllers\ThingController::class)->middleware('auth');
Route::resource('/transaction', \App\Http\Controllers\TransactionController::class)->middleware('auth');
Route::resource('/invoice', \App\Http\Controllers\InvoiceController::class)->middleware('auth');

app/Models/Thing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Thing extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price'
    ];

    public function transaction()
    {
        return $this->hasMany(Transaction::class);
    }
}

app/Http/Controllers/ThingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Thing;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class ThingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $things = Thing::latest()->paginate(false);
        return view('thing.index', compact('things'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('thing.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'     => 'required',
            'price'     => 'required',
        ]);

        Thing::create([
            'name' => $request->name,
            'price' => $request->price,
        ]);
        Alert::success('Barang', 'Barang baru telah ditambahkan!');
        return redirect()->route('thing.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Thing  $thing
     * @return \Illuminate\Http\Response
     */
    public function show(Thing $thing)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Thing  $thing
     * @return \Illuminate\Http\Response
     */
    public function edit(Thing $thing)
    {
        return view('thing.edit', compact('thing'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Thing  $thing
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thing $thing)
    {
        $this->validate($request, [
            'name'     => 'required',
            'price'   => 'required',
        ]);

        $thing->update([
            'name' => $request->name,
            'price' => $request->price,
        ]);
        Alert::warning('Barang', 'Barang telah diubah!');
        return redirect()->route('thing.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Thing  $thing
     * @return \Illuminate\Http\Response
     */
    public function destroy(Thing $thing)
    {
        $thing->delete();
        Alert::error('Barang', 'Barang telah dihapus!');
        return redirect()->route('thing.index');
    }
}

resources/views/thing/create.blade.php
@extends('layouts.master')
@section('title')
    Buat Barang Baru
@endsection

@section('content')
    <form action="{{ route('thing.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label class="font-weight-bold">Nama Barang</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                value="{{ old('name') }}" placeholder="Masukkan Nama Barang">

            <!-- error message untuk name -->
            @error('name')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="font-weight-bold">Harga Barang</label>
            <input type="number" class="form-control @error('price') is-invalid @enderror" name="price" id="price"
                value="{{ old('price') }}" placeholder="Masukkan harga barang">

            <!-- error message untuk price -->
            @error('price')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <button type="submit" class="btn btn-md btn-primary">Simpan</button>
        <button type="reset" class="btn btn-md btn-warning">Reset</button>

    </form>
@endsection

resources/views/thing/edit.blade.php
@extends('layouts.master')
@section('title')
    Buat Barang Baru
@endsection

@section('content')
    <form action="{{ route('thing.update', $thing->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label class="font-weight-bold">Nama Barang</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                value="{{ old('name', $thing->name) }}" placeholder="Masukkan Nama Barang">

            <!-- error message untuk name -->
            @error('name')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="font-weight-bold">Harga Barang</label>
            <input type="text" class="form-control @error('price') is-invalid @enderror" name="price" id="price"
                value="{{ old('price', $thing->price) }}" placeholder="Masukkan harga barang">

            <!-- error message untuk price -->
            @error('price')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <button type="submit" class="btn btn-md btn-primary">Simpan</button>
        <button type="reset" class="btn btn-md btn-warning">Reset</button>

    </form>
@endsection

resources/views/thing/index.blade.php
@extends('layouts.master')

@section('title')
    Barang
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{{ route('thing.create') }}" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Tambah Data Barang </span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nama Barang</th>
                            <th>Harga Barang</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                            <th>Pengaturan</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($things as $thing)
                            <tr>
                                <td>{{ $thing->name }}</td>
                                <td>{{ $thing->price }}</td>
                                <td>{{ $thing->created_at }}</td>
                                <td>{{ $thing->updated_at }}</td>
                                <td class="text-center">
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                        action="{{ route('thing.destroy', $thing->id) }}" method="POST">
                                        <a href="{{ route('thing.edit', $thing->id) }}"
                                            class="btn btn-sm btn-primary">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" align="center">No Data Recorded</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection