routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


Route::get('/master', function () {
    return view('layouts.master');
});

Route::resource('/thing', \App\Http\Controllers\ThingController::class)->middleware('auth');
Route::resource('/transaction', \App\Http\Controllers\TransactionController::class)->middleware('auth');
Route::resource('/invoice', \App\Http\Controllers\InvoiceController::class)->middleware('auth');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Thing;
use App\Models\Invoice;
use App\Models\Transaction;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::latest()->paginate(false);
        return view('transaction.index', compact('transactions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $invoices = Invoice::all();
        $things = Thing::all();
        return view('transaction.create', compact('invoices', 'things'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'invoice_id'     => 'required',
            'thing_id'     => 'required',
            'amount'     => 'required',
            'price'     => 'required',
        ]);

        Transaction::create([
            'invoice_id' => $request->invoice_id,
            'thing_id' => $request->thing_id,
            'amount' => $request->amount,
            'price' => $request->price,
            'grand' => $request->amount * $request->price,
        ]);
        Alert::success('Transaksi', 'Transaksi baru telah ditambahkan!');
        return redirect()->route('transaction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        $invoices = Invoice::all();
        $things = Thing::all();
        return view('transaction.edit', compact('transaction', 'invoices', 'things'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $this->validate($request, [
            'invoice_id'     => 'required',
            'thing_id'     => 'required',
            'amount'     => 'required',
            'price'     => 'required',
        ]);

        $transaction->update([
            'invoice_id' => $request->invoice_id,
            'thing_id' => $request->thing_id,
            'amount' => $request->amount,
            'price' => $request->price,
            'grand' => $request->amount * $request->price,
        ]);
        Alert::warning('Transaksi', 'Transaksi telah diubah!');
        return redirect()->route('transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->delete();
        Alert::error('Transaksi', 'Transaksi telah dihapus!');
        return redirect()->route('transaction.index');
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.master')
@section('title')
    Buat Transaksi Baru
@endsection

@section('content')
    <form action="{{ route('transaction.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label class="form-label" for="invoice_id">Nama Pembeli</label>
            <select class="form-control" id="invoice_id" name="invoice_id">
                @foreach ($invoices as $invoice)
                    <option value="{{ $invoice->id }}">{{ $invoice->buyer }}</option>
                @endforeach
            </select>
            <!-- error message untuk invoice_id -->
            @error('invoice_id')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="form-label" for="thing_id">Nama Barang</label>
            <select class="form-control" id="thing_id" name="thing_id">
                @foreach ($things as $thing)
                    <option value="{{ $thing->id }}">{{ $thing->name }}</option>
                @endforeach
            </select>
            <!-- error message untuk thing_id -->
            @error('thing_id')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="font-weight-bold">Amount</label>
            <input type="number" class="form-control @error('amount') is-invalid @enderror" name="amount"
                value="{{ old('amount') }}" placeholder="Masukkan banyaknya barang">

            <!-- error message untuk amount -->
            @error('amount')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="form-label" for="price">Harga Barang</label>
            <select class="form-control" id="price" name="price">
                @foreach ($things as $thing)
                    <option value="{{ $thing->price }}">{{ $thing->name }}</option>
                @endforeach
            </select>
            <!-- error message untuk price -->
            @error('price')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <button type="submit" class="btn btn-md btn-primary">Simpan</button>
        <button type="reset" class="btn btn-md btn-warning">Reset</button>

    </form>
@endsection

resources/views/transaction/edit.blade.php
@extends('layouts.master')
@section('title')
    Buat Transaksi Baru
@endsection

@section('content')
    <form action="{{ route('transaction.update', $transaction->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label class="form-label" for="invoice_id">Nama Pembeli</label>
            <select class="form-control" id="invoice_id" name="invoice_id">
                @foreach ($invoices as $invoice)
                    <option value="{{ $invoice->id }}">{{ $invoice->buyer }}</option>
                @endforeach
            </select>
            <!-- error message untuk invoice_id -->
            @error('invoice_id')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="form-label" for="thing_id">Nama Barang</label>
            <select class="form-control" id="thing_id" name="thing_id">
                @foreach ($things as $thing)
                    <option value="{{ $thing->id }}">{{ $thing->name }}</option>
                @endforeach
            </select>
            <!-- error message untuk thing_id -->
            @error('thing_id')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="font-weight-bold">Amount</label>
            <input type="number" class="form-control @error('amount') is-invalid @enderror" name="amount"
                value="{{ old('amount', $transaction->amount) }}" placeholder="Masukkan nama PIC customer">

            <!-- error message untuk amount -->
            @error('amount')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label class="form-label" for="price">Harga Barang</label>
            <select class="form-control" id="price" name="price">
                @foreach ($things as $thing)
                    <option value="{{ $thing->price }}">{{ $thing->name }}</option>
                @endforeach
            </select>
            <!-- error message untuk price -->
            @error('price')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
            @enderror
        </div>

        <button type="submit" class="btn btn-md btn-primary">Simpan</button>
        <button type="reset" class="btn btn-md btn-warning">Reset</button>

    </form>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.master')

@section('title')
    Transaction
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{{ route('transaction.create') }}" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Tambah Data Transaksi</span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nama Pembeli</th>
                            <th>Nama Barang</th>
                            <th>Amount</th>
                            <th>Price</th>
                            <th>Grand Total</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                            <th>Pengaturan</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($transactions as $transaction)
                            <tr>
                                <td>{{ $transaction->invoice->buyer }}</td>
                                <td>{{ $transaction->thing->name }}</td>
                                <td>{{ $transaction->amount }}</td>
                                <td>{{ $transaction->price }}</td>
                                <td>{{ $transaction->grand }}</td>
                                <td>{{ $transaction->created_at }}</td>
                                <td>{{ $transaction->updated_at }}</td>
                                <td class="text-center">
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                        action="{{ route('transaction.destroy', $transaction->id) }}" method="POST">
                                        <a href="{{ route('transaction.edit', $transaction->id) }}"
                                            class="btn btn-sm btn-primary">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" align="center">No Data Recorded</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection